version: "3.8"
services:
  db:
    container_name: db_mis
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password  --authentication_policy=mysql_native_password --lower_case_table_names=1
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 127.0.0.1:33060:3306

  app:
    depends_on:
      - db
    env_file: ./.env
    build: .
    ports:
      - 3000:3000
